services:
  api:
    image: irrationalintegral/fastapi
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    # command: >
      # sh -c "alembic upgrade head &&
             # uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}   # <--- THIS IS THE KEY FIX
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - WATCHFILES_FORCE_POLLING=true

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: